// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCofSBvLzU1WaUD9fQ0nkGloSUWtzgW5nY',
    appId: '1:1123723167:web:f99b804b0b57fdb80fbfaa',
    messagingSenderId: '1123723167',
    projectId: 'travel-app-eb807',
    authDomain: 'travel-app-eb807.firebaseapp.com',
    storageBucket: 'travel-app-eb807.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcXVk8M813FaiAZGU8Ep6LYg5Jyf4GGdg',
    appId: '1:1123723167:android:3dde253bcd0716cd0fbfaa',
    messagingSenderId: '1123723167',
    projectId: 'travel-app-eb807',
    storageBucket: 'travel-app-eb807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNKrBDngL2w7Vl6kx8ym6FpRzT3HTyCI',
    appId: '1:1123723167:ios:b52098711f31d45d0fbfaa',
    messagingSenderId: '1123723167',
    projectId: 'travel-app-eb807',
    storageBucket: 'travel-app-eb807.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFNKrBDngL2w7Vl6kx8ym6FpRzT3HTyCI',
    appId: '1:1123723167:ios:b52098711f31d45d0fbfaa',
    messagingSenderId: '1123723167',
    projectId: 'travel-app-eb807',
    storageBucket: 'travel-app-eb807.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCofSBvLzU1WaUD9fQ0nkGloSUWtzgW5nY',
    appId: '1:1123723167:web:e3bae2b5ccee13950fbfaa',
    messagingSenderId: '1123723167',
    projectId: 'travel-app-eb807',
    authDomain: 'travel-app-eb807.firebaseapp.com',
    storageBucket: 'travel-app-eb807.appspot.com',
  );
}
